// src/components/SpriteImage.tsx
import { convertFileSrc, invoke } from '@tauri-apps/api/core';
import { BiRegularCaretLeft, BiRegularCaretRight, BiRegularImageAlt } from 'solid-icons/bi';
import { Component, Show, createMemo, createResource, createSignal } from 'solid-js';
import { GraphicsResults } from '../definitions/GraphicsResults';
import { COMMAND_GET_GRAPHICS_FOR_IDENTIFIER } from '../lib/Constants';
import { toTitleCase } from '../lib/Utils';
import { useSettingsContext } from '../providers/SettingsProvider';

interface Dimensions {
  x: number;
  y: number;
}
export interface SpriteImageProps {
  identifier: string;
  class?: string;
}

interface SpriteImageDetail {
  graphicFilePath: string;
  offset: Dimensions;
  offset2: Dimensions;
  pageDim: Dimensions;
  tileDim: Dimensions;
  description?: string;
}

//Todo: Handle multiple sprites (either cycle between them or let user cycle between them)

const SpriteImage: Component<SpriteImageProps> = (props) => {
  const [currentSettings] = useSettingsContext();

  const [graphics] = createResource<GraphicsResults>(
    async () => {
      return await invoke(COMMAND_GET_GRAPHICS_FOR_IDENTIFIER, {
        options: {
          identifier: props.identifier,
          allGraphics: true,
        },
      });
    },
    {
      initialValue: {
        matchingGraphics: undefined,
        tilePages: [],
      },
    },
  );

  const [currentIndex, setCurrentIndex] = createSignal(0);

  const spriteDetails = createMemo((): SpriteImageDetail[] => {
    if (typeof graphics.latest.matchingGraphics === 'undefined' || graphics.latest.tilePages.length === 0) {
      return [
        {
          graphicFilePath: '',
          offset: { x: 0, y: 0 },
          offset2: { x: 0, y: 0 },
          tileDim: { x: 0, y: 0 },
          pageDim: { x: 0, y: 0 },
        },
      ];
    }
    const results: SpriteImageDetail[] = [];
    for (const graphic of graphics.latest.matchingGraphics) {
      // technically this is different for each isn't it...
      if (graphic.sprites && graphic.sprites.length > 0) {
        for (const sprite of graphic.sprites) {
          const tilePage = graphics.latest.tilePages.find((tp) => tp.identifier === sprite.tilePageId);
          if (tilePage.file.length > 0) {
            results.push({
              graphicFilePath: tilePage.file,
              offset: sprite.offset,
              offset2: sprite.offset2,
              tileDim: tilePage.tileDim,
              pageDim: tilePage.pageDim,
              description: sprite.primaryCondition || '',
            });
          }
        }
      } else if (graphic.layers.length > 0) {
        // const layer = graphic.layers[0][1][0];
        for (const [layerIdentifier, layers] of graphic.layers) {
          for (const layer of layers) {
            const tilePage = graphics.latest.tilePages.find((tp) => tp.identifier === layer.tilePageId);
            if (tilePage.file.length > 0) {
              results.push({
                graphicFilePath: tilePage.file,
                offset: layer.offset,
                offset2: layer.offset2,
                tileDim: tilePage.tileDim,
                pageDim: tilePage.pageDim,
                description: toTitleCase(`${layerIdentifier || ''} ${layer.layerName || ''}`),
              });
            }
          }
        }
      }
    }
    return results;
  });

  const [allowCycle, setAllowCycle] = createSignal(true);
  const [cycleTimeout, setCycleTimeout] = createSignal(setTimeout(() => {}, 0));

  function incrementIndex() {
    if (spriteDetails().length > 0) {
      if (currentIndex() + 1 >= spriteDetails().length) {
        setCurrentIndex(0);
      } else {
        setCurrentIndex(currentIndex() + 1);
      }
    } else {
      setCurrentIndex(0);
    }
  }

  function decrementIndex() {
    if (spriteDetails().length > 0) {
      if (currentIndex() - 1 < 0) {
        setCurrentIndex(spriteDetails().length - 1);
      } else {
        setCurrentIndex(currentIndex() - 1);
      }
    } else {
      setCurrentIndex(0);
    }
  }

  setInterval(() => {
    if (allowCycle() === true) {
      incrementIndex();
    }
  }, 5 * 1000);

  const assetUrl = createMemo(() => {
    if (spriteDetails().length > 0) {
      if (spriteDetails()[currentIndex()].graphicFilePath.length > 0) {
        const filePath = spriteDetails()[currentIndex()].graphicFilePath.replace(/\\/g, '/');
        const assetUrl = convertFileSrc(filePath);
        return assetUrl;
      }
    }
    return '';
  });

  const offsetX = createMemo(() => {
    let offX = spriteDetails()[currentIndex()].offset.x;
    if (spriteDetails()[currentIndex()].offset2 && spriteDetails()[currentIndex()].offset2.x > offX) {
      offX = spriteDetails()[currentIndex()].offset2.x;
    }
    return offX;
  });
  const offsetY = createMemo(() => {
    let offY = spriteDetails()[currentIndex()].offset.y;
    if (spriteDetails()[currentIndex()].offset2 && spriteDetails()[currentIndex()].offset2.y > offY) {
      offY = spriteDetails()[currentIndex()].offset2.y;
    }
    return offY;
  });
  const dimX = createMemo(() => {
    const scale = offsetX() - spriteDetails()[currentIndex()].offset.x + 1;
    return spriteDetails()[currentIndex()].tileDim.x * scale;
  });
  const dimY = createMemo(() => {
    const scale = offsetY() - spriteDetails()[currentIndex()].offset.y + 1;
    return spriteDetails()[currentIndex()].tileDim.y * scale;
  });
  const positionOffset = createMemo(() => {
    return `${
      spriteDetails()[currentIndex()].pageDim.x - (offsetX() + 1) * spriteDetails()[currentIndex()].tileDim.x + dimX()
    }px ${
      spriteDetails()[currentIndex()].pageDim.y - (offsetY() + 1) * spriteDetails()[currentIndex()].tileDim.y + dimY()
    }px`;
  });
  return (
    <Show
      when={currentSettings.displayGraphics && spriteDetails()[currentIndex()].graphicFilePath.length > 0}
      fallback={
        <div class='tooltip' data-tip={graphics.loading ? 'Loading graphics..' : 'No Graphics Found'}>
          <div
            class={`border-2 rounded-lg border-accent bg-black/50 ${props.class}`}
            style={{
              width: '32px',
              height: '32px',
              padding: '7px',
            }}>
            {graphics.loading ? (
              <div class='loading loading-dots loading-xs' style={{ width: '1rem', height: '1rem' }}></div>
            ) : (
              <BiRegularImageAlt />
            )}
          </div>
        </div>
      }>
      <div class={`border-2 rounded-lg border-accent bg-black/50 ${props.class} relative`}>
        <button
          class='absolute inset-y-0 -right-3'
          onClick={() => {
            setAllowCycle(false);
            incrementIndex();
            clearTimeout(cycleTimeout());
            setCycleTimeout(setTimeout(() => setAllowCycle(true), 15 * 1000));
          }}>
          <BiRegularCaretRight class='hover:text-accent' />
        </button>
        <button
          class='absolute inset-y-0 -left-3'
          onClick={() => {
            setAllowCycle(false);
            decrementIndex();
            clearTimeout(cycleTimeout());
            setCycleTimeout(setTimeout(() => setAllowCycle(true), 15 * 1000));
          }}>
          <BiRegularCaretLeft class='hover:text-accent' />
        </button>

        <span
          class='absolute -bottom-3 -left-6 text-center text-accent w-20'
          style={{
            'font-size': '0.5rem',
            'line-height': '0.5rem',
          }}>
          {spriteDetails()[currentIndex()].description}
        </span>
        <div
          style={{
            width: `${dimX()}px`,
            height: `${dimY()}px`,
            'background-image': `url("${assetUrl()}")`,
            'background-position': positionOffset(),
          }}></div>
      </div>
    </Show>
  );
};

export default SpriteImage;

// src/components/SpriteImage.svelte
<script lang="ts">
    import {
        ArrowLeft,
        ArrowRight,
        ChevronLeft,
        ChevronRight,
    } from "@lucide/svelte";
    import { invoke, convertFileSrc } from "@tauri-apps/api/core";
    import type { Dimensions } from "bindings/DFRawParser";
    import type { GraphicsResult } from "bindings/Structs";
    import { toTitleCase } from "helpers";

    let { identifier } = $props<{ identifier: string }>();

    let spriteData = $state<GraphicsResult[]>([]);
    let currentIdx = $state(0); // idx in sprite data
    let rotationInterval = 4;

    $effect(() => {
        invoke<GraphicsResult[]>("get_graphics", { identifier })
            .then((data) => (spriteData = data))
            .catch((error) => console.log(error));
    });

    setInterval(() => {
        if (spriteData.length === 0) return;

        currentIdx = (currentIdx + 1) % spriteData.length;
    }, rotationInterval * 1000);

    function backgroundPositionFromOffset(positionOffset: Dimensions): string {
        return `${positionOffset.x}px ${positionOffset.y}px`;
    }
</script>

<div>
    <span class="tx-xs"
        >{spriteData.length > currentIdx
            ? toTitleCase(spriteData[currentIdx].description, true)
            : "No sprites"}</span
    >
    <div class="w-9 h-9 border-2 border-accent rounded-lg bg-black/50 relative">
        {#if spriteData.length >= currentIdx && spriteData.length > 1}
            <div
                class="w-8 h-8"
                style:background-image={"url(" +
                    convertFileSrc(spriteData[currentIdx].filePath) +
                    ")"}
                style:background-position={backgroundPositionFromOffset(
                    spriteData[currentIdx].positionOffset,
                )}
            ></div>
            <button
                type="button"
                class="absolute inset-y-0 -right-3"
                onclick={() => {
                    currentIdx = (currentIdx + 1) % spriteData.length;
                }}
            >
                <ChevronRight
                    strokeWidth={4}
                    class="hover:text-base-200 text-primary h-3.5 w-3.5"
                />
            </button>
            <button
                type="button"
                class="absolute inset-y-0 -left-3"
                onclick={() => {
                    currentIdx =
                        (currentIdx - 1 + spriteData.length) %
                        spriteData.length;
                }}
            >
                <ChevronLeft
                    strokeWidth={4}
                    class="hover:text-base-200 text-primary h-3.5 w-3.5"
                />
            </button>
        {/if}

        <span
            class="absolute -bottom-3 -left-6 text-center text-accent w-20"
            style:font-size="0.5rem"
            style:line-height="0.5rem"
        >
            {spriteData.length > currentIdx
                ? toTitleCase(spriteData[currentIdx].description, true)
                : "No Graphic"}
        </span>
    </div>
</div>
